[versions]
minecraft = "1.21.1"
minecraftRange = "[1.21.1]"
neoForge = "21.1.206"
neoForgeRange = "[21.1.197,)"
neoForgeLoaderRange = "[5.3,)"
parchmentMappings = "2024.11.17"
terraBlenderRange = "[4,)"

[libraries]
kotlinForForge = { group = "thedarkcolour", name = "kotlinforforge-neoforge", version = "5.9.0" }
emi = { group = "dev.emi", name = "emi-neoforge", version = "1.1.22+1.21.1" }
cyanide = { group = "curse.maven", name = "cyanide-541676", version = "5782674" }

[plugins]
modDevGradle = { id = "net.neoforged.moddev", version = "+" }
shadow = { id = "com.gradleup.shadow", version = "+" }